<?php
/**
 * @link        http://www.phpcorner.net
 * @author      qingbing<780042175@qq.com>
 * @copyright   Chengdu Qb Technology Co., Ltd.
 */

namespace Zf\Helper\Plugins;


use Zf\Helper\Abstracts\Component;

class Qiniu extends Component
{
    protected function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
    }
}